# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addMedDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addMedDialog(object):
    def setupUi(self, addMedDialog):
        addMedDialog.setObjectName("addMedDialog")
        addMedDialog.resize(500, 800)
        self.titleLabel = QtWidgets.QLabel(addMedDialog)
        self.titleLabel.setGeometry(QtCore.QRect(140, 20, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.label_2 = QtWidgets.QLabel(addMedDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 93, 39))
        self.label_2.setObjectName("label_2")
        self.medNameInput = QtWidgets.QLineEdit(addMedDialog)
        self.medNameInput.setGeometry(QtCore.QRect(140, 120, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.medNameInput.setFont(font)
        self.medNameInput.setText("")
        self.medNameInput.setPlaceholderText("")
        self.medNameInput.setObjectName("medNameInput")
        self.label_3 = QtWidgets.QLabel(addMedDialog)
        self.label_3.setGeometry(QtCore.QRect(120, 420, 242, 39))
        self.label_3.setObjectName("label_3")
        self.timeEdit1 = QtWidgets.QTimeEdit(addMedDialog)
        self.timeEdit1.setGeometry(QtCore.QRect(250, 490, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeEdit1.setFont(font)
        self.timeEdit1.setWrapping(True)
        self.timeEdit1.setTime(QtCore.QTime(9, 0, 0))
        self.timeEdit1.setObjectName("timeEdit1")
        self.timeEdit2 = QtWidgets.QTimeEdit(addMedDialog)
        self.timeEdit2.setEnabled(False)
        self.timeEdit2.setGeometry(QtCore.QRect(250, 570, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeEdit2.setFont(font)
        self.timeEdit2.setWrapping(True)
        self.timeEdit2.setTime(QtCore.QTime(14, 0, 0))
        self.timeEdit2.setObjectName("timeEdit2")
        self.timeEdit3 = QtWidgets.QTimeEdit(addMedDialog)
        self.timeEdit3.setEnabled(False)
        self.timeEdit3.setGeometry(QtCore.QRect(250, 650, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeEdit3.setFont(font)
        self.timeEdit3.setWrapping(True)
        self.timeEdit3.setTime(QtCore.QTime(22, 0, 0))
        self.timeEdit3.setObjectName("timeEdit3")
        self.timingLabel1 = QtWidgets.QLabel(addMedDialog)
        self.timingLabel1.setGeometry(QtCore.QRect(80, 490, 150, 39))
        self.timingLabel1.setObjectName("timingLabel1")
        self.timingLabel2 = QtWidgets.QLabel(addMedDialog)
        self.timingLabel2.setEnabled(False)
        self.timingLabel2.setGeometry(QtCore.QRect(80, 570, 161, 39))
        self.timingLabel2.setObjectName("timingLabel2")
        self.medTimesSpinBox = QtWidgets.QSpinBox(addMedDialog)
        self.medTimesSpinBox.setGeometry(QtCore.QRect(50, 420, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.medTimesSpinBox.setFont(font)
        self.medTimesSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.medTimesSpinBox.setMinimum(1)
        self.medTimesSpinBox.setMaximum(3)
        self.medTimesSpinBox.setObjectName("medTimesSpinBox")
        self.timingLabel3 = QtWidgets.QLabel(addMedDialog)
        self.timingLabel3.setEnabled(False)
        self.timingLabel3.setGeometry(QtCore.QRect(80, 650, 161, 39))
        self.timingLabel3.setObjectName("timingLabel3")
        self.label_7 = QtWidgets.QLabel(addMedDialog)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 93, 39))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(addMedDialog)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 132, 39))
        self.label_8.setObjectName("label_8")
        self.qtySpinBox = QtWidgets.QSpinBox(addMedDialog)
        self.qtySpinBox.setGeometry(QtCore.QRect(180, 180, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qtySpinBox.setFont(font)
        self.qtySpinBox.setMinimum(1)
        self.qtySpinBox.setMaximum(9999)
        self.qtySpinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.qtySpinBox.setObjectName("qtySpinBox")
        self.qtyUnitComboBox = QtWidgets.QComboBox(addMedDialog)
        self.qtyUnitComboBox.setGeometry(QtCore.QRect(290, 180, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.qtyUnitComboBox.setFont(font)
        self.qtyUnitComboBox.setEditable(False)
        self.qtyUnitComboBox.setMaxVisibleItems(5)
        self.qtyUnitComboBox.setObjectName("qtyUnitComboBox")
        self.qtyUnitComboBox.addItem("")
        self.qtyUnitComboBox.addItem("")
        self.qtyUnitComboBox.addItem("")
        self.notesInput = QtWidgets.QTextEdit(addMedDialog)
        self.notesInput.setGeometry(QtCore.QRect(140, 250, 300, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesInput.sizePolicy().hasHeightForWidth())
        self.notesInput.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.notesInput.setFont(font)
        self.notesInput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notesInput.setObjectName("notesInput")
        self.okButton = QtWidgets.QPushButton(addMedDialog)
        self.okButton.setGeometry(QtCore.QRect(290, 750, 81, 31))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(addMedDialog)
        self.cancelButton.setGeometry(QtCore.QRect(390, 750, 81, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(addMedDialog)
        QtCore.QMetaObject.connectSlotsByName(addMedDialog)

    def retranslateUi(self, addMedDialog):
        _translate = QtCore.QCoreApplication.translate
        addMedDialog.setWindowTitle(_translate("addMedDialog", "Add Medicine"))
        self.titleLabel.setText(_translate("addMedDialog", "Add Medicine"))
        self.label_2.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Name:</span></p></body></html>"))
        self.label_3.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Time(s) in a day:</span></p></body></html>"))
        self.timeEdit2.setDisplayFormat(_translate("addMedDialog", "h:mm AP"))
        self.timeEdit3.setDisplayFormat(_translate("addMedDialog", "h:mm AP"))
        self.timingLabel1.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">1</span><span style=\" font-size:24pt; vertical-align:super;\">st</span><span style=\" font-size:24pt;\"> Timing:</span></p></body></html>"))
        self.timingLabel2.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">2</span><span style=\" font-size:24pt; vertical-align:super;\">nd</span><span style=\" font-size:24pt;\"> Timing:</span></p></body></html>"))
        self.timingLabel3.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">3</span><span style=\" font-size:24pt; vertical-align:super;\">rd</span><span style=\" font-size:24pt;\"> Timing:</span></p></body></html>"))
        self.label_7.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Notes:</span></p></body></html>"))
        self.label_8.setText(_translate("addMedDialog", "<html><head/><body><p><span style=\" font-size:24pt;\">Quantity:</span></p></body></html>"))
        self.qtyUnitComboBox.setCurrentText(_translate("addMedDialog", "pills"))
        self.qtyUnitComboBox.setItemText(0, _translate("addMedDialog", "pills"))
        self.qtyUnitComboBox.setItemText(1, _translate("addMedDialog", "ml"))
        self.qtyUnitComboBox.setItemText(2, _translate("addMedDialog", "mg"))
        self.notesInput.setPlaceholderText(_translate("addMedDialog", "write doctor\'s notes here"))
        self.okButton.setText(_translate("addMedDialog", "Ok"))
        self.cancelButton.setText(_translate("addMedDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addMedDialog = QtWidgets.QDialog()
    ui = Ui_addMedDialog()
    ui.setupUi(addMedDialog)
    addMedDialog.show()
    sys.exit(app.exec_())
